NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import subscriptions

urlpatterns = [
   path('admin/', admin.site.urls),
   path('new/', include('django.contrib.flatpages.urls')),
   # path('accounts/', include('django.contrib.auth.urls')),
   path('subscriptions/', subscriptions, name='subscriptions'),
   path('accounts/', include('allauth.urls')),
   path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path

from .views import (PostList, NewDetail, PostCreate, PostUpdate, PostDelete, PostSearch, subscriptions, CategoryListView)

from django.views.decorators.cache import cache_page
# Импортируем созданное нами представление


urlpatterns = [
    path('', cache_page(60 * 5)(PostList.as_view()), name='post_list'),
    path('<int:pk>/', cache_page(60 * 10)(NewDetail.as_view()), name='new_detail'),
    path('search/', PostSearch.as_view(), name='search'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('articles/create/', PostCreate.as_view(), name='articles_create'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='articles_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('articles/<int:pk>/delete/', PostDelete.as_view(), name='articles_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
    # path('categories/<int:pk>/subscriptions/', subscriptions, name='subscribe'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
# from django.conf import settings
from django.core.cache import cache


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = self.post_set.aggregate(pr=Coalesce(Sum('rating'), 0)).get('pr')
        comments_rating = self.user.comment_set.aggregate(cr=Coalesce(Sum('rating'),0)).get('cr')
        posts_comments_rating = self.post_set.aggregate(pcr=Coalesce(Sum('comment__rating'), 0)).get('pcr')

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name

    # def __str__(self):
    #     return f'{self.category}'
    #
    # def __str__(self):
    #     return self.name.title()


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128, unique=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('new_detail', args=[str(self.id)])

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:124] + '...'

    def __str__(self):
        return f'{self.title.title()} : {self.text[:20]}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news-{self.pk}')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.postThrough.title} | {self.categoryThrough.name}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )



templates/articles_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удалить статью</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удалить статью "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}


{% block title %}
   News List
{% endblock title %}

{% block content %}
<h1 class="text-center">Новости <span class="text-muted fs-6 fw-normal">Всего: {{ page_obj.paginator.count }}</span></h1>
    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscriptions' %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}

<hr>

    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
<!--    {% if perms.news.add_post %}-->
<!--    <a href="{% url 'post_create' %}">Добавить статью</a>-->
<!--    {% endif %}-->

{% if category_news_list %}

<div class="list-group">
    <br>
    {% for new in category_news_list %}
    <a href="{{ new.id }}" class="list-group-item list-group-item-action">
        <h3 style="..."><span
                style="...">{{ new.title }}</span></h3>
        <h6 style="..."><span
                style="...">Дата публикации: {{ new.dateCreation | date:'d M Y h:m:s' }}</span></h6>
        <h5 style="...">{{ new.text | truncatewords:20 }}</h5>
        <h6 style="..."><span
                style="...">Автор: {{ new.author.user }}</span></h6>
        <h6 style="..."><span
                style="...">Категории: </span>
        {% for cat in new.postCategory.all %}
            <a href="{% url 'category_list' cat.id %}">{{ cat }}</a>
        {% endfor %}</h6>
    </a>

    {% endfor%}
</div>
{% else %}
<h2>Ждем свежие новости</h2>
{% endif %}
<!--добавляем пагинацию-->

   {# Информация о предыдущих страницах #}
 {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
<!--   {{ page_obj.number }}-->

   {# Информация о следующих страницах #}
<!--   {% if page_obj.has_next %}-->
<!--       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>-->
<!--       {% if paginator.num_pages != page_obj.next_page_number %}-->
<!--           ...-->
<!--           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>-->
<!--       {% endif %}-->
<!--   {% endif %}-->


{% endblock content %}

templates/create_news.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>Сохранить новость "{{ object.name }}"?</p>
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2> Здраствуйте! Новые статьи за последнюю неделю </h2>
    <ul>
        {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2> Здраствуйте! Новая <a href="{{ link }}">статья</a> в вшем любимом разделе!</h2>
        <p>{{ text }}</p>
</body>
</html>

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action = "" method="post">
    {% csrf_token %}
    <p>Удалить новость"{{ object.name }}"?</p>
    <input type = "submit" value="Delete" />
</form>
{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Изменить новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>Изменить "{{ object.name }}"?</p>
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Search
{% endblock title %}

{% block content %}

   <h1>Найти статью </h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   <h2>Всего статей - {{ search|length }}</h2>
   {% if search %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Превью</td>
               <td>Автор</td>
               <td>Категория</td>
               <td>Тип</td>
               <td>Рейтинг</td>
           </tr>

           {% for po in search %}
           <tr>
               <td>{{ po.title | truncatewords:4 | censor }}</td>
               <td>{{ po.dateCreation | date:'d M Y' }}</td>
               <td>{{ po.text | truncatewords:20 | censor }}</td>
               <td>{{ po.author.user }}</td>
               <td>{% for category in po.postCategory.all %}{{ category.name }}{% endfor %}</td>
               <td>{{ po.categoryType }}</td>
               <td>{{ po.rating }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Статей нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscribe
{% endblock title %}

{% block content %}
<!--    <h1 class="text-center">{{ message }} {{category }}</h1>-->
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}